Basic/liongram/config/urls.py
from django.contrib import admin
from django.conf import settings      # settings.py 값들 가져오기
from django.conf.urls.static import static
from django.urls import path, include
from posts.views import index, url_view, url_parameter_view, function_view, class_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', url_view),
    path('url/<str:username>/', url_parameter_view),
    path('fbv/', function_view),
    path('cbv/', class_view.as_view()),

    # index 페이지 url
    path('', index, name='index'),

    # posts 앱으로 연결 
    path('posts/', include('posts.urls')),

    # django debug toolbar URL 설정
    path('__debug__/', include('debug_toolbar.urls')),

    # accounts 앱으로 연결
    path('accounts/', include('accounts.urls')),
]


# 이미지 파일 url 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Basic/liongram/posts/urls.py
from django.urls import path
from .views import post_list_view, post_create_view, post_update_view, post_detail_view, post_delete_view, post_create_form_view

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name='post-list'),
    # path('create/', post_create_view, name='post-create'),
    # Form를 사용하는 URL
    path('create/', post_create_form_view, name='post-create'),
    path('<int:id>/', post_detail_view, name='post-detail'),
    path('<int:id>/edit/', post_update_view, name='post-update'),
    path('<int:id>/delete/', post_delete_view, name='post-delete'),
]

Basic/liongram/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <title>{% block title %}{% endblock %} | 라이언그램</title>
</head>
<body class="container">
    <div>
        {% block content %}
        {% endblock %}
    </div>

    <div>
        <nav>
            <ul class="bottom-menu-group">
                <li>
                    <a href="{% url 'index' %}">
                        <img src="{% static 'icons/home_outlined_black_36dp.svg' %}" alt="홈"/>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <img src="{% static 'icons/search_outlined_black_36dp.svg' %}" alt="검색"/>
                    </a>
                </li>
                <li>
                    <a href="{% url 'posts:post-create' %}">
                        <img src="{% static 'icons/add_box_outlined_black_36dp.svg' %}" alt="글쓰기"/>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <img src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="좋아요"/>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <img src="{% static 'icons/account_circle_outlined_black_36dp.svg' %}" alt="프로필"/>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
    <!-- 로그인 여부 나타내기 -->
    {% if request.user.is_authenticated %}
        <span>로그인 상태 : {{ request.user.username }}님, 반갑습니다!</span>
    {% else %}
        <span>비로그인 상태</span>
    {% endif %}
</body>
</html>

Basic/liongram/templates/index.html
{% extends 'base.html' %}
{% load static %}

<!-- title block -->
{% block title %}홈{% endblock %}

<!-- content block -->
{% block content %}
<main>
    <div class="card-list">
        {% for post in post_list %}
            {% include 'mixin/posts/post_card.html' with detail=False %}
        {% endfor %}
    </div>
</main>
{% endblock %}