Basic/liongram/config/urls.py
from django.contrib import admin
from django.conf import settings      # settings.py 값들 가져오기
from django.conf.urls.static import static
from django.urls import path, include
from posts.views import index, url_view, url_parameter_view, function_view, class_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', url_view),
    path('url/<str:username>/', url_parameter_view),
    path('fbv/', function_view),
    path('cbv/', class_view.as_view()),

    # index 페이지 url
    path('', index, name='index'),

    # posts 앱으로 연결 
    path('posts/', include('posts.urls')),

    # django debug toolbar URL 설정
    path('__debug__/', include('debug_toolbar.urls')),

    # accounts 앱으로 연결
    path('accounts/', include('accounts.urls')),
]


# 이미지 파일 url 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Basic/liongram/posts/urls.py
from django.urls import path
from .views import post_list_view, post_create_view, post_update_view, post_detail_view, post_delete_view, post_create_form_view

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name='post-list'),
    # path('create/', post_create_view, name='post-create'),
    # Form를 사용하는 URL
    path('create/', post_create_form_view, name='post-create'),
    path('<int:id>/', post_detail_view, name='post-detail'),
    path('<int:id>/edit/', post_update_view, name='post-update'),
    path('<int:id>/delete/', post_delete_view, name='post-delete'),
]

Basic/liongram/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

# get_user_model() 함수를 이용해서 User모델 생성 -> 나중에 User모델을 쉽게 커스팀하기 위함
User = get_user_model()

# 게시판 모델
class Post(models.Model):
    image = models.ImageField(verbose_name='이미지', null=True, blank=True)
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    view_count = models.IntegerField(verbose_name='조회수', default=0)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)

# 댓글 모델
class Comment(models.Model):
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    post = models.ForeignKey(to='Post', on_delete=models.CASCADE)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)

Basic/liongram/posts/forms.py
from django import forms
from .models import Post
from django.core.exceptions import ValidationError

# class PostBaseForm(forms.Form):
#     CATEGORY_CHOICES = [
#         ('1', '일반'),
#         ('2', '계정'),
#     ]

#     image = forms.ImageField(label='이미지')
#     content = forms.CharField(label='내용', widget=forms.Textarea, required=True)
#     category = forms.ChoiceField(label='카테고리', choices=CATEGORY_CHOICES)    


# class PostCreateForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = '__all__'


class PostBaseForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'


class PostCreateForm(PostBaseForm):
    class Meta(PostBaseForm.Meta):
        fields = ['image', 'content']

    def clean_content(self):
        data = self.cleaned_data['content']
        if "비속어" == data:
            raise ValidationError("'비속어'는 사용하실 수 없습니다.")

        # Always return a value to use as the new cleaned data, even if
        # this method didn't change it.
        return data


class PostUpdateForm(PostBaseForm):
    class Meta(PostBaseForm.Meta):
        fields = ['image', 'content']


class PostDetailForm(PostBaseForm):
    def __init__(self, *args, **kwargs):
        super(PostDetailForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].widget.attrs['disabled'] = True

Basic/liongram/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
# 클래스 뷰를 위한 상속
from django.views.generic.list import ListView
from .models import Post
from django.contrib.auth.decorators import login_required
from django.http import Http404     # Http404를 import
from .forms import PostBaseForm, PostCreateForm, PostDetailForm

# Create your views here.


# index 페이지 연결하기
def index(request):
    post_list = Post.objects.all().order_by('-created_at')   # Post 전체 데이터 조회
    context = {
        'post_list': post_list,
    }

    return render(request, 'index.html', context)


# CRUD template 연결하기

def post_list_view(request):
    # post_list = Post.objects.all()   # Post 전체 데이터 조회
    post_list = Post.objects.filter(writer=request.user)    # Post.writer가 현재 로그인된 경우 조회
    context = {
        'post_list': post_list,
    }

    return render(request, 'posts/post_list.html', context)


def post_detail_view(request, id):
    try:
        post = Post.objects.get(id=id)        # 게시글 1개에 대한 데이터 가져오기
    except Post.DoesNotExist:
        return redirect('index')

    context = {
        'post': post,
        'form': PostDetailForm(),
    }

    return render(request, 'posts/post_detail.html', context)


@login_required                  # 로그인 되었을 경우에만 가능하게 하기
def post_create_view(request):
    if request.method == 'GET':
        return render(request, 'posts/post_form.html')
    else:
        image = request.FILES.get('image')             # 이미지 파일을 받을 경우, request.FILES로 사용
        content = request.POST.get('content')
        print(image)
        print(content)
        Post.objects.create(image=image, content=content, writer=request.user) # writer=request.user 추가 필요
        return redirect('index')



# forms.py를 이용해서 View 설정
def post_create_form_view(request):
    if request.method == 'GET':
        form = PostCreateForm()
        context = {
            'form': form,
        }
        return render(request, 'posts/post_form2.html', context)
    else:
        form = PostCreateForm(request.POST, request.FILES)

        # form 자체에 대한 유효성 검사
        if form.is_valid():
            Post.objects.create(image=form.cleaned_data['image'], content=form.cleaned_data['content'], writer=request.user) 
        else:
            return redirect('posts:post-create')
        
        return redirect('index')



@login_required                  # 로그인 되었을 경우에만 가능하게 하기
def post_update_view(request, id):
    # post = Post.objects.get(id=id)
    post = get_object_or_404(Post, id=id, writer=request.user)

    if request.method == 'GET':
        context = { 'post': post, }
        return render(request, 'posts/post_form.html', context)
    elif request.method == 'POST':
        new_image = request.FILES.get('image')
        content = request.POST.get('content')
        print(new_image)
        print(content)

        if new_image:
            post.image.delete()     # 기존의 이미지를 먼저 삭제
            post.image = new_image  # 그리고 새로운 이미지로 교체

        
        post.content = content
        post.save()
        return redirect('posts:post-detail', post.id)


@login_required                  # 로그인 되었을 경우에만 가능하게 하기
def post_delete_view(request, id):
    post = get_object_or_404(Post, id=id)

    if request.user != post.writer:
        raise Http404('잘못된 접근입니다.')

    if request.method == 'GET':
        context = {
        'post': post,
        }
        return render(request, 'posts/post_confirm_delete.html', context)
    else:
        post.delete()
        return redirect('index')

    
    






# HttpResponse 또는 JsonResponse 사용해보기
def url_view(request):
    print('url_view()')
    data = {'code': '001', 'msg': 'OK'}
    # return HttpResponse('<h1>url_view</h1>')
    return JsonResponse(data)


# url 변수 데이터 받아보기
def url_parameter_view(request, username):
    print('url_parameter_view()')
    print(f'username: {username}')
    print(f'request.GET: {request.GET}')
    return HttpResponse(username)


# Http method GET 또는 POST따라 데이터 받기
def function_view(request):
    print(f'request.method: {request.method}')
    if request.method == 'GET':
        print(f'request.GET: {request.GET}')
    elif request.method == 'POST':
        print(f'request.POST: {request.POST}')
    return render(request, 'view.html')


# Class View(ListView) 사용해보기
class class_view(ListView):
    model = Post
    ordering = ['-id']
    template_name = 'cbv_view.html'

Basic/liongram/templates/mixin/posts/post_card.html
{% load static %}
<div class="card">
    <!-- 카드 헤더 부분 -->
    <div class="card__header">
        <img class="card__user-image" src="http://via.placeholder.com/32x32" alt="프로필이미지"/>
        <a href="#">
            <span class="card__user-name">{{ post.writer }}</span>
        </a>
        {% if request.user == post.writer %}
            <a href="{% url 'posts:post-update' post.id %}">수정하기</a> |
            <a href="{% url 'posts:post-delete' post.id %}">삭제하기</a>
        {% endif %}
    </div>
    <!-- 카드 바디 부분 -->
    <div class="card__body">
        <!-- 포스트 이미지 -->
        <div>
            {% if post.image %}
                <img class="card__image" src="{{ post.image.url }}">
            {% else %}
                <img class="card__image" src="http://via.placeholder.com/600x600">
            {% endif %}    
        </div>
        <!-- 버튼 관련 -->
        <div class="card__btn-group">
            <div>
                <img class="card__btn" src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="좋아요"/>
                <img class="card__btn" src="{% static 'icons/mode_comment_outlined_black_36dp.svg' %}" alt="댓글"/>
                <img class="card__btn" src="{% static 'icons/send_outlined_black_36dp.svg' %}" alt="공유하기"/>
            </div>
            <div>
                <img class="card__btn" src="{% static 'icons/bookmark_outlined_black_36dp.svg' %}" alt="북마크"/>
            </div>
        </div>
        <!-- 포스트 내용 -->
        <div class="card_content">
            <span class="card__like-num">좋아요 00개</span>
            <div class="card__main-text">
                <p><span
                        class="card__user-name">{{ post.writer }}</span>
                        <!-- 디테일 페이지이면 내용 전부를 보여주기 -->
                        {% if not detail %}
                            {{ post.content|truncatechars:35 }}
                        {% else %}    
                            {{ post.content }}
                        {% endif %}
                        <!-- 디테일 페이지가 아니면 버튼 보여주기 -->
                        {% if not detail %}
                            <span><a href="{% url 'posts:post-detail' post.id %}">더보기</a></span>
                        {% endif %}
                </p>
            </div>
            <!-- 댓글 개수 및 내용 표시 -->
            <div>
                <p class="">댓글 {{ post.comment_set.all.count }}개 
                    {% if not detail %}
                            <span><a href="{% url 'posts:post-detail' post.id %}">모두 보기</a></span>
                    {% endif %}
                </p>
                <ul class="card__comment-group">
                    {% if not detail %}
                        {% for comment in post.comment_set.all|slice:":2" %}
                        <li>
                            <p><span class="card__user-name">{{ comment.writer }}</span>{{ comment.content }}</p>
                        </li>
                        {% endfor %}
                    {% else %}
                        {% for comment in post.comment_set.all %}
                            <li>
                                <p><span class="card__user-name">{{ comment.writer }}</span>{{ comment.content }}</p>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
            <span class="card__created-at">{{ post.created_at|date:"Y년 m월 d일" }}</span>
        </div>
    </div>
</div>