Basic/liongram/config/urls.py
from django.contrib import admin
from django.conf import settings      # settings.py 값들 가져오기
from django.conf.urls.static import static
from django.urls import path, include
from posts.views import index, url_view, url_parameter_view, function_view, class_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', url_view),
    path('url/<str:username>/', url_parameter_view),
    path('fbv/', function_view),
    path('cbv/', class_view.as_view()),

    # index 페이지 url
    path('', index, name='index'),

    # posts 앱으로 연결 
    path('posts/', include('posts.urls')),

    # django debug toolbar URL 설정
    path('__debug__/', include('debug_toolbar.urls')),

    # accounts 앱으로 연결
    path('accounts/', include('accounts.urls')),
]


# 이미지 파일 url 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Basic/liongram/posts/urls.py
from django.urls import path
from .views import post_list_view, post_create_view, post_update_view, post_detail_view, post_delete_view, post_create_form_view

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name='post-list'),
    # path('create/', post_create_view, name='post-create'),
    # Form를 사용하는 URL
    path('create/', post_create_form_view, name='post-create'),
    path('<int:id>/', post_detail_view, name='post-detail'),
    path('<int:id>/edit/', post_update_view, name='post-update'),
    path('<int:id>/delete/', post_delete_view, name='post-delete'),
]

Basic/liongram/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

# get_user_model() 함수를 이용해서 User모델 생성 -> 나중에 User모델을 쉽게 커스팀하기 위함
User = get_user_model()

# 게시판 모델
class Post(models.Model):
    image = models.ImageField(verbose_name='이미지', null=True, blank=True)
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    view_count = models.IntegerField(verbose_name='조회수', default=0)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)

# 댓글 모델
class Comment(models.Model):
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    post = models.ForeignKey(to='Post', on_delete=models.CASCADE)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)

Basic/liongram/posts/forms.py
from django import forms
from .models import Post
from django.core.exceptions import ValidationError

# class PostBaseForm(forms.Form):
#     CATEGORY_CHOICES = [
#         ('1', '일반'),
#         ('2', '계정'),
#     ]

#     image = forms.ImageField(label='이미지')
#     content = forms.CharField(label='내용', widget=forms.Textarea, required=True)
#     category = forms.ChoiceField(label='카테고리', choices=CATEGORY_CHOICES)    


# class PostCreateForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = '__all__'


class PostBaseForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'


class PostCreateForm(PostBaseForm):
    class Meta(PostBaseForm.Meta):
        fields = ['image', 'content']

    def clean_content(self):
        data = self.cleaned_data['content']
        if "비속어" == data:
            raise ValidationError("'비속어'는 사용하실 수 없습니다.")

        # Always return a value to use as the new cleaned data, even if
        # this method didn't change it.
        return data


class PostUpdateForm(PostBaseForm):
    class Meta(PostBaseForm.Meta):
        fields = ['image', 'content']


class PostDetailForm(PostBaseForm):
    def __init__(self, *args, **kwargs):
        super(PostDetailForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].widget.attrs['disabled'] = True

Basic/liongram/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
# 클래스 뷰를 위한 상속
from django.views.generic.list import ListView
from .models import Post
from django.contrib.auth.decorators import login_required
from django.http import Http404     # Http404를 import
from .forms import PostBaseForm, PostCreateForm, PostDetailForm

# Create your views here.


# index 페이지 연결하기
def index(request):
    post_list = Post.objects.all().order_by('-created_at')   # Post 전체 데이터 조회
    context = {
        'post_list': post_list,
    }

    return render(request, 'index.html', context)


# CRUD template 연결하기

def post_list_view(request):
    # post_list = Post.objects.all()   # Post 전체 데이터 조회
    post_list = Post.objects.filter(writer=request.user)    # Post.writer가 현재 로그인된 경우 조회
    context = {
        'post_list': post_list,
    }

    return render(request, 'posts/post_list.html', context)


def post_detail_view(request, id):
    try:
        post = Post.objects.get(id=id)        # 게시글 1개에 대한 데이터 가져오기
    except Post.DoesNotExist:
        return redirect('index')

    context = {
        'post': post,
        'form': PostDetailForm(),
    }

    return render(request, 'posts/post_detail.html', context)


@login_required                  # 로그인 되었을 경우에만 가능하게 하기
def post_create_view(request):
    if request.method == 'GET':
        return render(request, 'posts/post_form.html')
    else:
        image = request.FILES.get('image')             # 이미지 파일을 받을 경우, request.FILES로 사용
        content = request.POST.get('content')
        print(image)
        print(content)
        Post.objects.create(image=image, content=content, writer=request.user) # writer=request.user 추가 필요
        return redirect('index')



# forms.py를 이용해서 View 설정
def post_create_form_view(request):
    if request.method == 'GET':
        form = PostCreateForm()
        context = {
            'form': form,
        }
        return render(request, 'posts/post_form2.html', context)
    else:
        form = PostCreateForm(request.POST, request.FILES)

        # form 자체에 대한 유효성 검사
        if form.is_valid():
            Post.objects.create(image=form.cleaned_data['image'], content=form.cleaned_data['content'], writer=request.user) 
        else:
            return redirect('posts:post-create')
        
        return redirect('index')



@login_required                  # 로그인 되었을 경우에만 가능하게 하기
def post_update_view(request, id):
    # post = Post.objects.get(id=id)
    post = get_object_or_404(Post, id=id, writer=request.user)

    if request.method == 'GET':
        context = { 'post': post, }
        return render(request, 'posts/post_form.html', context)
    elif request.method == 'POST':
        new_image = request.FILES.get('image')
        content = request.POST.get('content')
        print(new_image)
        print(content)

        if new_image:
            post.image.delete()     # 기존의 이미지를 먼저 삭제
            post.image = new_image  # 그리고 새로운 이미지로 교체

        
        post.content = content
        post.save()
        return redirect('posts:post-detail', post.id)


@login_required                  # 로그인 되었을 경우에만 가능하게 하기
def post_delete_view(request, id):
    post = get_object_or_404(Post, id=id)

    if request.user != post.writer:
        raise Http404('잘못된 접근입니다.')

    if request.method == 'GET':
        context = {
        'post': post,
        }
        return render(request, 'posts/post_confirm_delete.html', context)
    else:
        post.delete()
        return redirect('index')

    
    






# HttpResponse 또는 JsonResponse 사용해보기
def url_view(request):
    print('url_view()')
    data = {'code': '001', 'msg': 'OK'}
    # return HttpResponse('<h1>url_view</h1>')
    return JsonResponse(data)


# url 변수 데이터 받아보기
def url_parameter_view(request, username):
    print('url_parameter_view()')
    print(f'username: {username}')
    print(f'request.GET: {request.GET}')
    return HttpResponse(username)


# Http method GET 또는 POST따라 데이터 받기
def function_view(request):
    print(f'request.method: {request.method}')
    if request.method == 'GET':
        print(f'request.GET: {request.GET}')
    elif request.method == 'POST':
        print(f'request.POST: {request.POST}')
    return render(request, 'view.html')


# Class View(ListView) 사용해보기
class class_view(ListView):
    model = Post
    ordering = ['-id']
    template_name = 'cbv_view.html'

Basic/liongram/templates/posts/post_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

<!-- title block -->
{% block title %}글 삭제{% endblock %}

<!-- content block -->
{% block content %}
<h1>Post 삭제 화면</h1>
<form action="" method="POST">
    {% csrf_token %}
    <p>한번 삭제된 데이터는 복구가 불가능합니다.</p><br>
    <p>그래도 삭제하시겠습니까?</p><br>
    <a href="{% url 'index' %}">돌아가기</a>
    <input type="submit" value="삭제하기">
</form>
<hr>
{% include 'mixin/posts/post_card.html' with detail=True %}
{% endblock %}

Basic/liongram/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}

<!-- title block -->
{% block title %}글 상세{% endblock %}

<!-- content block -->
{% block content %}
<h1>Post 상세 화면</h1>
{% include 'mixin/posts/post_card.html' with detail=True %}
{{ form.as_p }}
{% endblock %}

Basic/liongram/templates/posts/post_form.html
{% extends 'base.html' %}

<!-- title block -->
{% block title %}글 입력{% endblock %}

<!-- content block -->
{% block content %}
<h1>Post 입력 화면</h1>
<!-- 이미지 전송을 위한 인코딩 방식 추가 -->
<form action="" method="POST" enctype="multipart/form-data"> 
    {% csrf_token %}
    <!-- 이미지 입력 -->
    <div>
        <label for="id_image">이미지</label>
        {% if post.image %}
        <p>현재 : <a href="{{ post.image.url }}">{{ post.image.name }}</a></p>
        <p>변경 : <input type="file" name="image" accept="image/*" id="id_image"></p>
        {% else %}
            <input type="file" name="image" accept="image/*" id="id_image">
        {% endif %} 
    </div>
    <!-- 내용 입력 -->
    <div>
        <label for="id_content">내용</label>
        <textarea name="content" id="id_content" cols="30" rows="10">
            {% if post %}
                {{ post.content }}
            {% endif %}    
        </textarea>
    </div>
    <!-- 데이터 전송  -->
    <div>
        <input type="submit">
    </div>
</form>
{% endblock %}

Basic/liongram/templates/posts/post_form2.html
{% extends 'base.html' %}

<!-- title block -->
{% block title %}글 입력{% endblock %}

<!-- content block -->
{% block content %}
<h1>Post 입력 화면 - Form 사용</h1>
<!-- 이미지 전송을 위한 인코딩 방식 추가 -->
<form action="" method="POST" enctype="multipart/form-data"> 
    {% csrf_token %}

    <!-- forms.py 사용 -->
    <div>
        {{ form.as_p }}
        <!-- {% for field in form %}
            {{ field.label }}
            {{ field }}
        {% endfor %} -->
    </div>
    <!-- 데이터 전송  -->
    <div>
        <input type="submit">
    </div>
</form>
{% endblock %}

Basic/liongram/templates/posts/post_list.html
{% extends 'base.html' %}

<!-- title block -->
{% block title %}글 목록{% endblock %}

<!-- content block -->
{% block content %}
<h1>Post 목록 화면</h1>

{% for post in post_list %}
    <div>
        {{ post.id }}
        {{ post.image }}
        {{ post.content }}
        {{ post.created_at }}
        {{ post.writer }}
    </div>
{% endfor %}

{% endblock %}